name: Install Checker Quick
on: 
  push:
    branches-ignore:
      - main
      - dev
  pull_request:
    branches-ignore:
      - main
      - dev
jobs:

    test-python-os-versions:
        name: Check Python ${{ matrix.python-version }} on ${{ matrix.runs-on }} on ${{ matrix.architecture }}
        continue-on-error: ${{ matrix.allow_failure }}
        runs-on: ${{ matrix.runs-on }}
        strategy:
            fail-fast: false
            matrix:
                allow_failure: [false]
                runs-on: [ubuntu-latest] 
                architecture: [x86_64]
                python-version: ["3.10", "3.12"]
                # Currently no public runners available for this but this or arm64 should work next time
                # include:
                #     - python-version: "3.10"
                #       architecture: [aarch64]
                #       runs-on: macos-latest
                #       allow_failure: true
        steps:
            - uses: actions/checkout@v4
            
            - name: Setup Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install repo
              run: |
                python -m pip install .
            - name: Check installation
              run: |
                python -c "import py4DSTEM; print(py4DSTEM.__version__)"
            # - name: Check machine arch
            #   run: |
            #     python -c "import platform; print(platform.machine())"
