name: Lint with super-linter@v5-slim

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v5 # updated to latest slim as quicker to download 
        env:
          VALIDATE_ALL_CODEBASE: false # only check changes
          VALIDATE_PYTHON_FLAKE8: true # lint with flake8
          DEFAULT_BRANCH: "dev" # set default branch to dev
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # for github things
          # FILTER_REGEX_EXCLUDE: .*test/.* # exclude test dirs
          FILTER_REGEX_EXCLUDE: .*__init__.py/.* # exclude test dirs
          FILTER_REGEX_INCLUDE: .*py4DSTEM/.* # only look for py4DSTEM
          LINTER_RULES_PATH: / # set toplevel dir as the path to look for rules
          PYTHON_FLAKE8_CONFIG_FILE: .flake8 # set specific config file
